
# PyMOL script for SHV-27 and SHV-28 3D visualization
# Generated by Segulah-L 2.0

fetch AF293345  # SHV-27 reference in PDB (if available)
fetch AF299299  # SHV-28 reference

# Color by secondary structure
color red, ss h
color yellow, ss s
color green, ss l

# Show cartoon representation
show cartoon

# Label important residues
# Active site S70
select active_site, resi 70
show spheres, active_site
color magenta, active_site

# Zoom
zoom

# Save session
save shv_comparison.pse
